# Generated by Django 4.2.16 on 2024-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_empresa', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('contato', models.CharField(max_length=14, null=True)),
                ('end', models.CharField(max_length=45, null=True)),
                ('tipo', models.CharField(max_length=15, null=True)),
                ('comp', models.CharField(max_length=15, null=True)),
                ('num', models.CharField(max_length=5, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_registro', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'default_related_name': 'dentals',
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('primeiro_nome', models.CharField(max_length=200, null=True)),
                ('segundo_nome', models.CharField(max_length=200, null=True)),
                ('nome_completo', models.CharField(max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('cep', models.CharField(max_length=14, null=True)),
                ('contato', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('sexo', models.CharField(max_length=15, null=True)),
                ('tipo', models.CharField(max_length=15, null=True)),
                ('data_nascimento', models.DateField(help_text='Informe a data no formato dd/mm/aaaa', null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'default_related_name': 'dentistas',
            },
        ),
    ]
